version: '3.8'

services:
  latex-compiler:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./storage:/app/storage
      - texmf-data:/texmf
      - latex-cache:/root/.texlive
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
      - TEXMFHOME=/texmf
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  texmf-data:
  latex-cache:
