export enum SIGNUP_RETURN_TYPES {
    ERROR = 'ERROR',
    ALREAD_REGISTERED_ERROR = 'ALREADY_REGISTERED',
    CONFIRM_EMAIL = 'CONFIRM_EMAIL'
}

export enum SIGNIN_RETURN_TYPES {
    ERROR = 'ERROR',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    SUCCESS = 'SUCCESS'
}